### ISSUE TITLE
I don't understand how it works

### ISSUE THREAD

**Issue by THEVOLCO** [digitalseraphim/MobSpawnTweaks#1]
Hi,
I'm having trouble at understanding how your mod works. I would e.g. like to disable the spawning of blizzes(from thermal foundation) in the erebus dimension(id=66) .For that i added following to the config file:
dimension.66 {
  S:blacklist <
  mods.cofh.thermalfoundation.entity.monster.EntityBlitz

> }

But this doesn't work. Can you help me pls?

**Comment by digitalseraphim** [comment]
Can you try just putting EntityBlitz in the list? I'm sorry, it's been a long time since I've looked at this mod and don't have anything set up on my new computer.

**Comment by THEVOLCO** [comment]
I tried this:
dimension.66 {
  S:blacklist <
  EntityBlitz

> }

But it doesn't work. It only creates some type of error config file.

**Comment by digitalseraphim** [comment]
Can you post your error log somewhere I can look at it?

**Comment by digitalseraphim** [comment]
One other thing is that this is only for up to Minecraft 1.7.10, and Forge 10.13.2.1291

**Comment by THEVOLCO** [comment]
I guess that could be the problem. Will you update your mod?

**Comment by digitalseraphim** [comment]
What version of forge are you using. It probably won't be today, but I can try to update it

**Comment by THEVOLCO** [comment]
Omg that would be awesome. Im using version 10.13.4.1614.

**Comment by digitalseraphim** [comment]
Over on curseforge there's a new version .5 that should work for you. I even improved performance drastically, so thanks! (If it's not there, give it a little time, as I think it has to be approved). Please let me know if it works for you! http://minecraft.curseforge.com/projects/mobspawntweaks/files

**Comment by digitalseraphim** [comment]
Have you been able to give the new version a try? 

(Closing issue in 3 days if no response.)
